### ISSUE TITLE
Pyomo 5.6 installation fails on Windows

### ISSUE THREAD

**Issue by jrlooker** [Pyomo/pyomo#808]
Hi,

It appears Pyomo 5.6 installation fails on Windows (7, at least) as the installation requires Visual Studio C++, due to Cython code. If I hack setup.py setting using_cython=False, then installation is successful.

I believe assuming Cython will work "out of the box" on Windows is problematic. See
https://github.com/cython/cython/wiki/InstallingOnWindows

Can you please fix this?

Thanks.

**Comment by jsiirola** [comment]
Can you provide a little more context? What python interpreter are you using, and how are you installing Pyomo?  My understanding from looking at the `setup.py` is that installation should still proceed if either Cython is unavailable of a compilation step fails.

**Comment by jrlooker** [comment]
Thanks for responding so quickly.

Anaconda Python 3.6.4. Installing Pyomo using pip 9.0.1. I think setup.py effectively checks if Cython is installed. This is not the problem as Cython is distributed with Anaconda and the cythonize function works fine. On Windows, you also need the correct C-compiler for Cython to work (as discussed in the above link). Here's the error:

"error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools"

I haven't tried getting this version of Microsoft Visual C++.  

This issue does not occur on Linux and macOS.

**Comment by jrlooker** [comment]
I just checked: I already have Microsoft Visual C++ 14.

**Comment by jsiirola** [comment]
The install should still succeed, as the call to `cythonize` is within a try-except. Can you post the full error and stack trace?

**Comment by jrlooker** [comment]
I can't send you the full stack trace. A usual Python stack trace is not produced, and cythonize seems to work as usual. It's the C-compilation that's failing. Here's the full error:

Building wheels for collected packages: Pyomo
  Running setup.py bdist_wheel for Pyomo: started
  Running setup.py bdist_wheel for Pyomo: finished with status 'error'
  running build_ext
  building 'pyomo.core.expr.expr_pyomo5' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
  
  ----------------------------------------
  Running setup.py clean for Pyomo
Failed to build Pyomo
    building 'pyomo.core.expr.expr_pyomo5' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------
  Rolling back uninstall of pyomo

Note that I already have Microsoft Visual C++ 14.

**Comment by jrlooker** [comment]
Thanks, John.

**Comment by jrlooker** [comment]
Unfortunately, Pyomo 5.6.1 has not fixed installation issues on my Windows system. See issue #808 for details of my system.

The setup.py seems to initially behave as expected, rerunning installation when C compilation fails. But  on the second attempt, this exception is returned:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-l3ehpgtw-build\setup.py, line 197, in <module>
        if 'Microsoft Visual C++' not in e_info.message:
    AttributeError: 'SystemExit' object has no attribute 'message'

Can this be fixed please?

**Comment by jrlooker** [comment]
I obtained the setup.py file from pypi about 1 hour ago.

**Comment by blnicho** [comment]
Looks like this was fixed a couple days after the release in #823

**Comment by blnicho** [comment]
I'm going to close this again as technically this is fixed on master. As @jsiirola mentioned you can access the fix by installing directly from Github.

**Comment by jrlooker** [comment]
Thanks. Is setup.py the only difference?

**Comment by jsiirola** [comment]
Yes, I think so.

**Comment by jrlooker** [comment]
Hi. I'm sorry, but installation of Pyomo 5.6.6 still crashes on my Windows 7 machine. The details are essentially the same as above, but now I'm using Python 3.7.3 from Anaconda. Again, disabling Cython in setup.py fixes the issue.

**Comment by jrlooker** [comment]
I just tested this on a fresh Windows 10 machine, and the same crash occurs.

**Comment by blnicho** [comment]
@jrlooker could you provide the command you are using to install Pyomo? Did you make sure to uninstall all old versions of Pyomo before installing 5.6.6? I have not been able to reproduce this locally (running Anaconda on a Windows 10 machine).

**Comment by jrlooker** [comment]
I'm installing in an environment where I don't have direct access to the internet, so the command I use is:

pip -v install --no-index --upgrade Pyomo-5.6.6.tar.gz.

Note: I run this after running pip with the same options to install Pyomo's dependencies that aren't already included in Anaconda (appdirs and PyUtilib).

The Windows 10 machine is new and so did not have any previous version of Pyomo installed.

I think the issue is I don't have Microsoft Visual C++ build tools installed. I believe this shouldn't be required as Cython compilation is not required.

**Comment by jrlooker** [comment]
I just installed Microsoft Visual C++ build tools on my Windows 10 machine, and this fixed the issue.
